services:
  eureka-server:
    build: .
    container_name: pushcode-eureka
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - pushcode-network

networks:
  pushcode-network:
    external: true