services:
  security-server:
    build:
      context: ./security-service
    container_name: pushcode-security
    ports:
      - "8082:8082"
    networks:
      - pushcode-network
    restart: always

networks:
  pushcode-network:
    external: true