spring:
  application:
    name: execution-service

execution:
  max-time-seconds: 10
  idle-timeout-seconds: 15
  memory-limit: 256m
  cpu-limit: 0.5

docker:
  images:
    python: pushcode-python
    c: pushcode-c
    cpp: pushcode-cpp
    java: pushcode-java

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

  instance:
    prefer-ip-address: true