spring:
  application:
    name: execution-service

  mongodb:
    uri: mongodb+srv://pushpakmjaiswal:Jaiswalpm%4026@cluster0.tjonnlq.mongodb.net/pushcodeSecurity?appName=Cluster0


app:
  jwt:
    secret: AmbUrBYyJUbFJcGpbfPzz2ipdibr-ajtNGK3sRV2xUuj3aYzxx96_wHqnf3YKaRCwQnLAAQIu0GgXcLHNzUQvA
    expiration-ms: 3600000

execution:
  max-time-seconds: 10
  idle-timeout-seconds: 15
  memory-limit: 256m
  cpu-limit: 0.5

docker:
  images:
    python: pushcode-python
    c: pushcode-c
    cpp: pushcode-cpp
    java: pushcode-java

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

  instance:
    prefer-ip-address: true